## Page d'accueil
louvre_order :
    path:    /
    defaults:    {_controller: LouvreShopBundle:Booking:index}

## Page de paiement
louvre_payment :
    path:    /order/payment
    defaults:    {_controller: LouvreShopBundle:Booking:orderPayment}

## Page de confirmation
louvre_confirmation :
    path:    /order/confirmation
    defaults:    {_controller: LouvreShopBundle:Booking:orderConfirmation}

## Mentions légales
louvre_ticket_mentions:
    path:     /legal
    defaults: { _controller: LouvreShopBundle:Booking:mentionsView}

## Web service quota
louvre_webservice_quota:
    path:     /webservice/booking/quota
    defaults: { _controller: LouvreShopBundle:Webservice:quota}
    methods: [POST]

## Recuperation ticket
louvre_recovery :
    path:    /order/recovery
    defaults:    {_controller: LouvreShopBundle:Booking:orderRecovery}
    methods: [POST]

