services:
#    louvre_shop.example:
#        class: Louvre\ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    louvre_shop.validator.order.check:
        class: Louvre\ShopBundle\Validator\OrderCheckValidator
        arguments: ["@doctrine.orm.entity_manager", "@=container", "%max_purchase_item%"]
        tags:
            - { name: validator.constraint_validator, alias: louvre.order.check }

    louvre_shop.webservice:
        class: Louvre\ShopBundle\Webservice\Webservice
        arguments: ["@doctrine.orm.entity_manager", "%max_capacity%", "%max_purchase_item%"]

    louvre_shop.order:
        class: Louvre\ShopBundle\Order\Order
        arguments: ["@doctrine.orm.entity_manager"]
