services:
#    louvre_shop.example:
#        class: Louvre\ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    louvre_shop.validator.order.check:
        class: Louvre\ShopBundle\Validator\OrderCheckValidator
        arguments: ["@doctrine.orm.entity_manager", "@=container", "%max_purchase_item%"]
        tags:
            - { name: validator.constraint_validator, alias: louvre.order.check }

    louvre_shop.validator.birthday.check:
        class: Louvre\ShopBundle\Validator\BirthdayCheckValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: louvre.birthday.check }

    louvre_shop.webservice:
        class: Louvre\ShopBundle\Webservice\Webservice
        arguments: ["@doctrine.orm.entity_manager", "%max_capacity%", "%max_purchase_item%"]

    louvre_shop.order:
        class: Louvre\ShopBundle\Order\Order
        arguments: ["@doctrine.orm.entity_manager", "@request_stack", "@louvre_shop.email"]

    louvre_shop.payment:
        class: Louvre\ShopBundle\Payment\Payment
        arguments: ["@doctrine.orm.entity_manager", "%stripe_key%"]


    louvre_shop.email:
        class: Louvre\ShopBundle\Mailer\Mailer
        arguments: ["@service_container", "%mailer_from%", "%mailer_reply%", "%mailer_name%"]
